import { ListingResponse } from '../types';

export const listingsMock: ListingResponse[] = [
  {
    id: 1,
    company: {
      id: 0,
      slug: '',
      name: '',
      name_internal: '',
      website: '',
      industry: '',
      descr: '',
      logo: '',
      cover: '',
    },
    contact: {
      name: '',
      email: '',
      phone: '',
      photo: undefined,
    },
    descr: '',
    employment_type: '',
    experience: '',
    from_date: '',
    function: '',
    language: '',
    locations: [],
    slug: '',
    title: 'Mock Listing 1',
    urls: {
      ad: '',
      apply: '',
    },
    video: {
      url: '',
    },
    owner: {
      id: 0,
      name: '',
      email: '',
    },
    skills: '',
    application_date_is_hidden: false,
  },
  {
    id: 2,
    company: {
      id: 0,
      slug: '',
      name: '',
      name_internal: '',
      website: '',
      industry: '',
      descr: '',
      logo: '',
      cover: '',
    },
    contact: {
      name: '',
      email: '',
      phone: '',
      photo: undefined,
    },
    descr: '',
    employment_type: '',
    experience: '',
    from_date: '',
    function: '',
    language: '',
    locations: [],
    slug: '',
    title: 'Mock Listing 2',
    urls: {
      ad: '',
      apply: '',
    },
    video: {
      url: '',
    },
    owner: {
      id: 0,
      name: '',
      email: '',
    },
    skills: '',
    application_date_is_hidden: false,
  },
];
